apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: relationships
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: ${CLOWDAPP_NAME}
      namespace: ${NAMESPACE}
    spec:
      envName: ${ENV_NAME}
      replicas: 1
      deployments:
        - name: relationships
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            livenessProbe:
              httpGet:
                path: /livez
                port: 8000
            readinessProbe:
              httpGet:
                path: /readyz
                port: 8000
          webServices:
            public:
              enabled: true
              apiPath: authz
parameters:
  - description: Name of the ClowdApp
    name: CLOWDAPP_NAME
    value: relationships
  - description : ClowdEnvironment name
    name: ENV_NAME
    value: insights-ephemeral
  - description: Namespace to deploy into
    name: NAMESPACE
    value: ${NAMESPACE}
  - description: App Image
    name: IMAGE
    value: ${IMAGE}
  - description: Image Tag
    name: IMAGE_TAG
    value: ${IMAGE_TAG}
