apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: relationships
objects:
  - apiVersion: authzed.com/v1alpha1
    kind: SpiceDBCluster
    metadata:
      name: ${CLOWDAPP_NAME}-spicedb
    spec:
      config:
        datastoreEngine: memory
      secretName: dev-spicedb-config
  - apiVersion: v1
    kind: Secret
    metadata:
      name: dev-spicedb-config
    stringData:
      preshared_key: "averysecretpresharedkey"
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: ${CLOWDAPP_NAME}
      namespace: ${NAMESPACE}
    spec:
      envName: ${ENV_NAME}
      replicas: 1
      deployments:
        - name: relationships
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            livenessProbe:
              httpGet:
                path: /livez
                port: 8000
            readinessProbe:
              httpGet:
                path: /readyz
                port: 8000
            env:
              - name: SPICEDB_PRESHARED
                value: /config/spicedb/preshared_key
              - name: SPICEDB_ENDPOINT
                value: relationships-spicedb.${NAMESPACE}.svc.cluster.local:50051
            volumes:
              - name: spicedb-token
                secret:
                  secretName: dev-spicedb-config
            volumeMounts:
              - name: spicedb-token
                mountPath: /config/spicedb
          webServices:
            public:
              enabled: true
              apiPath: authz
parameters:
  - description: Name of the ClowdApp
    name: CLOWDAPP_NAME
    value: relationships
  - description : ClowdEnvironment name
    name: ENV_NAME
    value: insights-ephemeral
  - description: Namespace to deploy into
    name: NAMESPACE
    value: ${NAMESPACE}
  - description: App Image
    name: IMAGE
    value: ${IMAGE}
  - description: Image Tag
    name: IMAGE_TAG
    value: ${IMAGE_TAG}
