server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  spiceDb:
    useTLS: false
    endpoint: localhost:50051
    tokenFile: spicedb_pre_shared
