server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  spiceDb:
    useTLS: false
    endpoint: spicedb:50051
    token: "${SPICEDB_PRESHARED:foobar}"
